### ISSUE TITLE
Any workaround for `bad CPU type in executable`?

### ISSUE THREAD

**Issue by pelted** [msanders/setup#1]
I know the project is a little old, but I dusted off my Zero.sh dot files for a new M1 and while updating the defaults for the newish keys I get `bad CPU type in executable: apply-user-defaults`

**Comment by msanders** [comment]
Thanks for reporting. I just pushed an update for `apply-user-defaults` to be compatible with Apple Silicon so it will run without requiring Rosetta. If you're using the `zero-sh` tap, it should be fixed by running `brew update && brew upgrade apply-user-defaults`.

**Comment by pelted** [comment]
Nice! That worked. Taking the "_figure out how to get `apply-user-defaults` working and PR it_" off my weekend todo list.

**Comment by pelted** [comment]
Nice! That worked. Taking the "figure out how to get apply-user-defaults working and PR it" off my weekend todo list.
